config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get 'orders/new'
    post 'orders/confirm' => '/orders/confirm'
    get 'orders/completion'
    post 'orders/create' => '/order'
    get  'orders' => 'orders#index'
    get  'orders/:id' => 'orders#show', as: 'show_order'
    get 'cart_items' => 'cart_items#index'
    patch 'cart_items/:id' => 'cart_items#update', as: 'update_cart_item'
    delete 'cart_items/destroy_all' => '/cart_items/destroy_all'              #-優先順位を考慮-httpメソッドとURLが被ってる場合、idは下に書く
    delete 'cart_items/:id' => 'cart_items#destroy', as: 'destroy_cart_item'  #-優先順位を考慮
    post 'cart_items/create' => '/cart_item'
    get 'customers/mypage' => 'customers#show', as: 'mypage_customers'
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customers'
    patch 'customers/update/:id' => 'customers#update', as: 'update_customer'
    get 'customers/confirm'
    patch 'customers/withdrawal' => '/customers/withdrawal'
    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'show_items'
    get '/' => 'homes#top'
    get 'about' => 'homes#about'
  end


  namespace :admin do

    get '/' => 'homes#top'
    get 'orders/:id' => 'orders#show', as: 'show_order'
    get 'customers/index' => '/admin/customer'
    get 'customers/:id' => 'customers#show', as: 'show_customer'
    get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/:id' => 'customers#update', as: 'update_customer'
    get 'items' => 'items#index'
    get 'items/new' => '/admin/items/new'
    post 'items/create' => 'items'
    get 'items/:id' => 'items#show', as: 'show_item'
    get 'items/:id/edit' => 'items#edit', as: 'edit_item'
    patch 'items/:id' => 'items#update', as: 'update_item'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  ##消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @items = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_show_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_show_item_path(item.id)
  end
  
  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:price)
    
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container px-8"><!--このpxはpadding x方向を意味する。pyはy方向。-->
  <div class="row">
    <div class="col-md-4">
      <h3>商品編集</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <%= form_with model: @item, url: admin_update_item_path(@item.id), method: :patch do |f| %>
      <table>
        <tr>
          <th>
            <div class="field">
                <%= f.label :商品画像 %>
            </div>
          </th>
          <td>
            <%= f.file_field :image, accept:"image/*" %>
          </td>
        </tr>
        <tr>
          <th>
            <div class="field">
                <%= f.label :商品名 %>
            </div>
          </th>
          <td>
            <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
          </td>
        </tr>
        <tr>
          <th>
            <div class="field">
              <%= f.label :商品説明 %>
            </div>
          </th>
          <td>
            <%= f.text_field :introduction, autofocus: true, autocomplete: "introducton" %>
          </td>
        </tr>
        <tr>
          <th>
            <div class="field">
              <%= f.label :税抜価格 %>
            </div>
          </th>
          <td>
            <%= f.number_field :price, autofocus: true, autocomplete: "price" %>
          </td>
        </tr>
      </table>
        <div class="actions">
          <%= f.submit "変更を保存", class:'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="contaier px-5">
 <div class="row">
   <div class="col-md-10">
     <h2>商品一覧</h2>
   </div>
   <div class="col-md-2">
    <%= link_to admin_items_new_path do %>
      <p>商品新規登録</p>
     <% end %>
   </div>
 </div>
 <div class="row">
  <div class="col-md-8 offset-md-1">
   <!--itemindexの記述-->
    
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th colspan="3"></th>
          </tr>
       </thead>
       <tbody>
        <% @items.each do |item| %>
        <tr>
          <td>
            <%= item.id %>
          </td>
          <td>
            <%= link_to admin_show_item_path(item.id) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td>
            <%= item.price %>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-3">
      <h3>商品新規登録</h3>
    </div>
  </div>
    <div class="col-md-7 offset-md-1">
      <%= form_with model: @items, url: admin_items_create_path do |f| %>
        <div class="field">
            <%= f.label :商品画像 %>
            <%= f.file_field :image, accept:"image/*" %>
        </div>
      
        <div class="field">
            <%= f.label :商品名 %>
            <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
      
        <div class="field">
            <%= f.label :商品説明 %>
            <%= f.text_field :introduction, autofocus: true %>
        </div>
        
        <div class="field">
            <%= f.label :税抜価格 %>
            <%= f.number_field :price, autofocus: true, autocomplete: "price" %>円
        </div>
      
        <div class="actions">
          <%= f.submit "新規登録", class:'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
    

app/views/admin/items/show.html.erb
<!--itemshowの記述-->
<div class="container px-5">
  <div class="row">
    <div class="col-md-3">
      <h3>商品詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.get_image(100,100) %>
    </div>
    <div class="col-md-8">
      <table>
        <tr>
          <th>商品名</th>
          <td>
           <%= @item.name %>
          </td>
        <tr>
          <th>商品説明</th>
          <td>
            <%= @item.introduction %>
          </td>
        </tr>
        <tr>
          <th>税込価格<br>
              (税抜価格)
          </th>
          <td>
            <%= @item.price %>
           (<%= @item.with_tax_price %>)円
          </td>
        </tr>
        <tr>
          <th>
          </th>
          <td>
            <%= link_to admin_edit_item_path(@item.id),class:"btn btn-success btn-sm" do %>
              <p>編集する</p>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>