config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get 'orders/new'
    post 'orders/confirm' => '/orders/confirm'
    get 'orders/completion'
    post 'orders/create' => '/order'
    get  'orders' => 'orders#index'
    get  'orders/:id' => 'orders#show', as: 'show_order'
    get 'cart_items' => 'cart_items#index'
    patch 'cart_items/:id' => 'cart_items#update', as: 'update_cart_item'
    delete 'cart_items/destroy_all' => '/cart_items/destroy_all'              #-優先順位を考慮-httpメソッドとURLが被ってる場合、idは下に書く
    delete 'cart_items/:id' => 'cart_items#destroy', as: 'destroy_cart_item'  #-優先順位を考慮
    post 'cart_items/create' => '/cart_item'
    get 'customers/mypage' => 'customers#show', as: 'mypage_customers'
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customers'
    patch 'customers/update/:id' => 'customers#update', as: 'update_customer'
    get 'customers/confirm'
    patch 'customers/withdrawal' => '/customers/withdrawal'
    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'show_items'
    get '/' => 'homes#top'
    get 'about' => 'homes#about'
  end


  namespace :admin do

    get '/' => 'homes#top'
    get 'orders/:id' => 'orders#show', as: 'show_order'
    get 'customers/index' => '/admin/customer'
    get 'customers/:id' => 'customers#show', as: 'show_customer'
    get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/:id' => 'customers#update', as: 'update_customer'
    get 'items' => 'items#index'
    get 'items/new' => '/admin/items/new'
    post 'items/create' => 'items'
    get 'items/:id' => 'items#show', as: 'show_item'
    get 'items/:id/edit' => 'items#edit', as: 'edit_item'
    patch 'items/:id' => 'items#update', as: 'update_item'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def full_name                       #フルネーム用のメソッドを
    self.last_name + self.first_name 
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_show_customer_path(@customer.id)
    else
      render 'edit' #遷移先でインスタンス変数を使っているため、updateでもインスタンス変数を使用している。
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
  <div class="container px-5,py-10">
    <%= form_with model: @customer,url: admin_update_customer_path do |f| %>
    <% if @customer.errors.any? %>                               <!--エラーテンプレ文-->
      <div id="error_explanation" class="alert alert-danger">     
        <ul>                                                      
          <% @customer.errors.full_messages.each do |message| %>  
            <li><%= message %></li>                               
          <% end %>                                               
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md">
        <h2>
         <%= @customer.full_name %>の会員情報編集
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <p>会員ID</p>
        <%= @customer.id %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <p>氏名</p>
      </div>
      <div class="col-md-4">
        <div class="field">
            <%= f.text_field :last_name, autofocus: true, autocomplete: "family-name" %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="field">
            <%= f.text_field :first_name, autofocus: true, autocomplete: "given-name" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <p>フリガナ</p>
      </div>
      <div class="col-md-4">
        <div class="field">
            <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "name" %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="field">
            <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "name" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        郵便番号
      </div>
      <div class="col-md-4">
        <div class="field">
            <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal-code" %>
        </div>
      </div>
      <div class="col-md-5">
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <p>住所</p>
      </div>
      <div class="col-md-9">
        <div class="field">
            <%= f.text_field :address, autofocus: true, autocomplete: "street-address" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        電話番号
      </div>
      <div class="col-md-4">
        <div class="field">
            <%= f.text_field :telephone_number, autofocus: true, autocomplete: "tel" %>
        </div>
      </div>
      <div class="col-md-5">
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <p>メールアドレス</p>
      </div>
      <div class="col-md-4">
        <div class="field">
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
      </div>
      <div class="col-md-5">
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-4">
        <div class="actions">
          <%= f.submit "変更を保存" %>
        </div>
      </div>
      <div class="col-md-5">
      </div>
    </div>
    <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div class="contaier">
 <div class="row">
  <div class="col-md-8 offset-md-1">
   <!--customerindexの記述-->
    <h2>会員一覧</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
       </thead>
       <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= customer.id %>
          </td>
          <td>
            <%= link_to admin_show_customer_path(customer.id) do %>
              <%= customer.full_name %>
            <% end %>
          </td>
          <td>
            <%= customer.email %>
          </td>
          <td>
            <% if customer.is_deleted == false %>
            <%= "有効" %>
            <% else %>
            <%= "無効" %>
            <% end %><!--会員ステータスを書く-->
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!--customershowの記述-->
<div class="container px-5 py-5">
  <div class="row">
    <div class="col-md-8">
      <h3>
           <%= @customer.full_name %>さんの会員詳細
      </h3>
      <table>
        <tr>
          <th>
            会員ID
          </th>
          <td>
            <%= @customer.id %>
          </td>
        </tr>
        <tr>
          <th>
            氏名
          </th>
          <td>
            <%= @customer.last_name %> <%= @customer.first_name %>
          </td>
        </tr>
        <tr>
          <th>
            フリガナ
          </th>
          <td>
            <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
          </td>
        </tr>
        <tr>
          <th>
            郵便番号
          </th>
          <td>
            <%= @customer.postal_code %>
          </td>
        </tr>
        <tr>
          <th>
            住所
          </th>
          <td>
            <%= @customer.address %>
          </td>
        </tr>
        <tr>
          <th>
            電話番号
          </th>
          <td>
            <%= @customer.telephone_number %>
          </td>
        </tr>
        <tr>
          <th>
            メールアドレス
          </th>
          <td>
            <%= @customer.email %>
          </td>
        </tr>
        <tr>
          <th>
           会員ステータス
          </th>
          <td>
            <% if @customer.is_deleted == false %>
            <%= "有効" %>
            <% else %>
            <%= "無効" %>
            <% end %><!--会員ステータスを書く-->
          </td>
        </tr>
      </table>

        <%= link_to admin_edit_customer_path(@customer.id),class:"btn btn-success" do %>
          <p>編集する</p>
        <% end %>
        <%= link_to admin_path,class:"btn btn-primary" do %>
          <p>注文履歴一覧を見る</p>
        <% end %>
    </div>
  </div>
</div>