config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get 'orders/new'
    post 'orders/confirm' => '/orders/confirm'
    get 'orders/completion'
    post 'orders/create' => '/order'
    get  'orders' => 'orders#index'
    get  'orders/:id' => 'orders#show', as: 'show_order'
    get 'cart_items' => 'cart_items#index'
    patch 'cart_items/:id' => 'cart_items#update', as: 'update_cart_item'
    delete 'cart_items/destroy_all' => '/cart_items/destroy_all'              #-優先順位を考慮-httpメソッドとURLが被ってる場合、idは下に書く
    delete 'cart_items/:id' => 'cart_items#destroy', as: 'destroy_cart_item'  #-優先順位を考慮
    post 'cart_items/create' => '/cart_item'
    get 'customers/mypage' => 'customers#show', as: 'mypage_customers'
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customers'
    patch 'customers/update/:id' => 'customers#update', as: 'update_customer'
    get 'customers/confirm'
    patch 'customers/withdrawal' => '/customers/withdrawal'
    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'show_items'
    get '/' => 'homes#top'
    get 'about' => 'homes#about'
  end


  namespace :admin do

    get '/' => 'homes#top'
    get 'orders/:id' => 'orders#show', as: 'show_order'
    get 'customers/index' => '/admin/customer'
    get 'customers/:id' => 'customers#show', as: 'show_customer'
    get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/:id' => 'customers#update', as: 'update_customer'
    get 'items' => 'items#index'
    get 'items/new' => '/admin/items/new'
    post 'items/create' => 'items'
    get 'items/:id' => 'items#show', as: 'show_item'
    get 'items/:id/edit' => 'items#edit', as: 'edit_item'
    patch 'items/:id' => 'items#update', as: 'update_item'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def full_name                       #フルネーム用のメソッドを
    self.last_name + self.first_name 
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  ##消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  ##消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_show_customer_path(@customer.id)
    else
      render 'edit' #遷移先でインスタンス変数を使っているため、updateでもインスタンス変数を使用している。
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page])#order(created_at: :desc)で並び順を
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @items = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_show_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_show_item_path(item.id)
  end
  
  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:price)
    
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @postage = 800
    @total_price = 0
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  protected
  def after_sign_in_path_for(resource)
    admin_path
  end
  
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<script src="https://kit.fontawesome.com/78bcbcecca.js" crossorigin="anonymous"></script>-->
  </head>

  <body>
      <header>
           <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>cake</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if admin_signed_in? %>
            <% if request.fullpath.include? "/admin" %>
                <!--admin側のheaderを返す-->
            <li>
              <a class="nav-link text-light" href="/admin/items/">
                商品一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/admin/customers/index">
                会員一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/admin">
                注文履歴一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/admin/sign_out">
                ログアウト
              </a>
            </li>
            <% else %>
                <!--user側のheaderを返す-->
            <li>
              <a class="nav-link text-light" href="/about">
                About
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/items">
                商品一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/customers/sign_up">
                新規登録
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/customers/sign_in">
                ログイン
              </a>
            </li>
            <% end %>
          <% elsif customer_signed_in? %>
              <!--customerログイン状態の際に、表示したいheaderのメニューを記載-->
            <li>
              <%= link_to mypage_customers_path(current_customer),class:"nav-link text-light" do %> <!--hrefでログインユーザーページを指定する方法がわからない-->
                マイページ                                    <!-- link to passの形に書き換えて解決。パスの後にclass指定することで、CSSを適応させることができる。-->
              <% end %>
            </li>
            <li>
              <a class="nav-link text-light" href="/items">
                商品一覧
              </a>
            </li>
            <li>
              <%= link_to cart_items_path(current_customer),class:"nav-link text-light" do %> <!--hrefでログインユーザーページを指定する方法がわからない-->
                カート                                    <!-- link to passの形に書き換えて解決。パスの後にclass指定することで、CSSを適応させることができる。-->
              <% end %>
            </li>
            <li>
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/customers/sign_out">
                ログアウト
              </a>
            </li>
            <% else %>
            <li>
              <a class="nav-link text-light" href="/about">
                About
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/items">
                商品一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/customers/sign_up">
                新規登録
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/customers/sign_in">
                ログイン
              </a>
            </li><!-- adminでもcustomerでもログインしていない時に表示するheaderのメニューを記載 -->
          <% end %>
          </div>
          </div>
        </nav>
    </header>
    <%= yield %>
    <footer>
     <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p></p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>